SELECT * FROM PHONEINFO_BASIC;
SELECT * FROM PHONEINFO_UNIV;
SELECT * FROM PHONEINFO_COM;


-- PHONEINFO_BASIC INSERT
INSERT INTO PHONEINFO_BASIC (IDX, FR_NAME, FR_PHONNUMBER, FR_EMAIL, FR_ADDRESS, FR_REGDATE)
    VALUES(1, '유재석', '010-1111-1111', 'ASD@GAMIL.COM', '서대문구', SYSDATE);
INSERT INTO PHONEINFO_BASIC (IDX, FR_NAME, FR_PHONNUMBER, FR_EMAIL, FR_ADDRESS, FR_REGDATE)
    VALUES(2, '이광수', '010-2222-2222', 'QWE@NAVER.COM', '은평구', SYSDATE);
INSERT INTO PHONEINFO_BASIC (IDX, FR_NAME, FR_PHONNUMBER, FR_EMAIL, FR_ADDRESS, FR_REGDATE)
    VALUES(3, '지석진', '010-3333-3333', 'ZXC@GAMIL.COM', '마포구', SYSDATE);
INSERT INTO PHONEINFO_BASIC (IDX, FR_NAME, FR_PHONNUMBER, FR_EMAIL, FR_ADDRESS, FR_REGDATE)
    VALUES(4, '김종국', '010-4444-4444', 'QAZ@GAMIL.COM', '종로구', SYSDATE);
    
-- PHONEINFO_UNIV INSERT
INSERT INTO PHONEINFO_UNIV (IDX, FR_U_MAJOR, FR_U_YEAR, FR_REF)
    VALUES(1, '이과', 4, 1);
 INSERT INTO PHONEINFO_UNIV (IDX, FR_U_MAJOR, FR_U_YEAR, FR_REF)
    VALUES(2, '문과', 3, 2);
 INSERT INTO PHONEINFO_UNIV (IDX, FR_U_MAJOR, FR_U_YEAR, FR_REF)
    VALUES(3, '컴공', 1, 3);
 INSERT INTO PHONEINFO_UNIV (IDX, FR_U_MAJOR, FR_U_YEAR, FR_REF)
    VALUES(4, '영어', 2, 4);
    
-- PHONEINFO_COM INSERT
INSERT INTO PHONEINFO_COM (IDX, FR_C_COMPANY, FR_REF)
    VALUES(1, '런닝맨1', 1);
INSERT INTO PHONEINFO_COM (IDX, FR_C_COMPANY, FR_REF)
    VALUES(2, '런닝맨2', 2);
INSERT INTO PHONEINFO_COM (IDX, FR_C_COMPANY, FR_REF)
    VALUES(3, '런닝맨3', 3);
INSERT INTO PHONEINFO_COM (IDX, FR_C_COMPANY, FR_REF)
    VALUES(4, '런닝맨4', 4);  

-- PHONEINFO_BASIC SELECT
SELECT * FROM PHONEINFO_BASIC;
SELECT * FROM PHONEINFO_BASIC WHERE IDX=2;

-- PHONEINFO_UNIV SELECT
SELECT FR_NAME, FR_aDDRESS
FROM PHONEINFO_BASIC P1, PHONEINFO_UNIV P2
WHERE P1.IDX=P2.FR_REF;

-- PHONEINFO_COM SELECT
SELECT P1.FR_NAME, P3.FR_C_COMPANY
FROM PHONEINFO_BASIC P1, PHONEINFO_COM P3
WHERE P1.IDX=P3.FR_REF;

-- PHONEINFO_BASIC UPDATE
UPDATE PHONEINFO_BASIC
SET FR_EMAIL='유재석@GMAIL', FR_ADDRESS='압구정'
WHERE IDX=1; --FR_NAME='유재석';

-- PHONEINFO_UNIV UPDATE
UPDATE PHONEINFO_UNIV
SET FR_U_YEAR=2
WHERE IDX=3;

-- PHONEINFO_COM UPDATE
UPDATE PHONEINFO_COM
SET FR_C_COMPANY='삼성'
WHERE IDX=1;

-- PHONEINFO_BASIC DELETE
DELETE FROM PHONEINFO_BASIC
WHERE IDX=1;

-- PHONEINFO_UNIV DELETE
DELETE FROM PHONEINFO_UNIV
WHERE IDX=1;

-- PHONEINFO_COM DELETE
DELETE FROM PHONEINFO_COM
WHERE IDX=1;


