-- 2021.06.14

-- SUB QUERY

-- 스칼라 부속 질의 : SELECT 절 이후에 사용
-- 단일 행 단일 열 값이 사용된다.
SELECT O.CUSTID, (SELECT C.NAME FROM CUSTOMER C WHERE O.CUSTID=C.CUSTID) AS NAME
FROM ORDERS O;

-- EMP 테이블만 사용해서 사원 이름, 부서이름 출력
SELECT E.ENAME, (SELECT D.DNAME FROM DEPT D WHERE E.DEPTNO=D.DEPTNO) AS DNAME 
FROM EMP E;

-- 마당서점의 고객별
-- 판매액을 보이시오
-- (결과는 고객이름과 고객별 판매액을 출력).
-- JOIN
SELECT C.CUSTID, C.NAME, SUM(O.SALEPRICE) AS "판매액"
FROM ORDERS O, CUSTOMER C
WHERE O.CUSTID=C.CUSTID
GROUP BY C.CUSTID, C.NAME;

SELECT * FROM ORDERS;

-- 스칼라 부속질의 이용
SELECT CUSTID, (SELECT NAME FROM CUSTOMER C WHERE O.CUSTID=C.CUSTID) AS NAME, SUM(O.SALEPRICE) AS "구매액"
FROM ORDERS O
GROUP BY CUSTID;

-- 인라인 뷰 : FROM 절 뒤에 사용되는 부속질의, 가상 테이블 처럼 사용
-- 고객번호가 2 이하인 -> CUSTOMER
-- 고객의 판매액을 보이시오  -> ORDERS
-- (결과는 고객이름과 고객별 판매액 출력)
SELECT O.CUSTID, C.NAME, SUM(O.SALEPRICE)
FROM (SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID<=2) C, ORDERS O
WHERE C.CUSTID=O.CUSTID
GROUP BY O.CUSTID, C.NAME;

-- 중첩질의 : WHERE 절 뒤에 사용하는 부속질의
-- 비교연산자를 이용할 때는 단일행 단일열의 결과를 같는 부속질의를 사용
-- > < = != >= <=
-- 평균 급여보다 더 많은 급여를 받는 사원을 검색
SELECT *
FROM EMP
WHERE SAL > (SELECT AVG(SAL) FROM EMP) --> 평균 급여
ORDER BY SAL;

SELECT AVG(SAL) FROM EMP; -- 평균급여

-- 평균 주문금액 이하의 주문에 대해서
-- 주문번호와 금액을 보이시오. --> ORDERS
SELECT *
FROM ORDERS
WHERE SALEPRICE > (SELECT AVG(SALEPRICE) FROM ORDERS)
ORDER BY SALEPRICE;

--평균 주문금액
SELECT AVG(SALEPRICE) FROM ORDERS;

-- 각 고객의 평균 주문금액보다 
-- 큰 금액의 주문 내역에 대해서 
-- 주문번호, 고객번호, 금액을 보이시오.

SELECT *
FROM ORDERS O1
WHERE SALEPRICE > (SELECT AVG(SALEPRICE) 
                    FROM ORDERS O2 
                    WHERE O2.CUSTID=O1.CUSTID);

SELECT AVG(SALEPRICE) FROM ORDERS O2 WHERE O2.CUSTID=O1.CUSTID;
SELECT AVG(SALEPRICE) FROM ORDERS O2 WHERE CUSTID=4;

-- 다중행 연산자 IN
-- 3000 이상 받는 사원이 소속된 부서와 동일한 부서에서 근무하는 사원 리스트 출력
SELECT DISTINCT DEPTNO FROM EMP WHERE SAL >= 3000;
SELECT * 
FROM EMP
WHERE DEPTNO IN (SELECT DISTINCT DEPTNO FROM EMP WHERE SAL >= 3000);

-- 대한민국에 거주하는 고객에게 
-- 판매한 도서의 총 판매액을 구하시오.
SELECT SUM(SALEPRICE)
FROM ORDERS
WHERE CUSTID IN (SELECT CUSTID FROM CUSTOMER WHERE ADDRESS LIKE '%대한민국%')
;

SELECT CUSTID FROM CUSTOMER WHERE ADDRESS LIKE '%대한민국%';

-- 3번 고객이 주문한 도서의 최고 금액
-- 보다 더 비싼 도서를 구입한 주문의
-- 주문번호와 금액을 보이시오.
SELECT ORDERID, SALEPRICE
FROM ORDERS
--WHERE SALEPRICE > (SELECT MAX(SALEPRICE)
--                    FROM ORDERS
--                    WHERE CUSTID=3);
--
WHERE SALEPRICE > ALL (SELECT SALEPRICE FROM ORDERS WHERE CUSTID=3);

-- 3번 고객이 주문한 도서의 최고 금액
SELECT MAX(SALEPRICE)
FROM ORDERS
WHERE CUSTID=3;

SELECT SALEPRICE FROM ORDERS WHERE CUSTID=3;

-- EXISTS 연산자로 대한민국에 거주하는 고객에게 
-- 판매한 도서의 총 판매액을 구하시오.
SELECT SUM(SALEPRICE)
FROM ORDERS O
WHERE EXISTS (SELECT * FROM CUSTOMER C WHERE O.CUSTID=C.CUSTID AND C.ADDRESS LIKE '%대한민국%');

SELECT * FROM CUSTOMER C WHERE 2=C.CUSTID AND C.ADDRESS LIKE '%대한민국%';
SELECT * FROM CUSTOMER C WHERE 3=C.CUSTID AND C.ADDRESS LIKE '%대한민국%';
SELECT * FROM CUSTOMER C WHERE 4=C.CUSTID AND C.ADDRESS LIKE '%대한민국%';
SELECT * FROM CUSTOMER C WHERE 5=C.CUSTID AND C.ADDRESS LIKE '%대한민국%';