CREATE TABLE PHONEINFO_BASIC (
    IDX NUMBER(6) PRIMARY KEY, 
    FR_NAME VARCHAR2(20) NOT NULL,          
    FR_PHONNUMBER VARCHAR2(20) NOT NULL,    
    FR_EMAIL VARCHAR2(20),                  
    FR_ADDRESS VARCHAR2(20),                
    FR_REGDATE DATE DEFAULT SYSDATE        
);

CREATE TABLE PHONEINFO_UNIV (
    IDX NUMBER(6) PRIMARY KEY,
    FR_U_MAJOR VARCHAR2(20) DEFAULT 'N' NOT NULL,
    FR_U_YEAR NUMBER(1) DEFAULT '1' NOT NULL,
    FR_REF NUMBER(7) REFERENCES PHONEINFO_BASIC(IDX) NOT NULL
);

CREATE TABLE PHONEINFO_COM (
    IDX NUMBER(6) PRIMARY KEY,
    FR_C_COMPANY VARCHAR2(20) DEFAULT 'N' NOT NULL,
    FR_REF NUMBER(6) REFERENCES PHONEINFO_BASIC(IDX) NOT NULL
);