-- 2021.06.16

-- view

-- 자주 사용되는
-- 30번 부서에 소속된 사원들의 사번과 이름과 부서번호를 출력하기 위한
-- SELECT 문을 하나의 뷰로 정의해 봅시다.

CREATE OR REPLACE VIEW EMP_VIEW30
AS
SELECT EMPNO, ENAME, DEPTNO
FROM EMP
WHERE DEPTNO=30;

SELECT * FROM emp_view30
WHERE ENAME = 'JAMES';

-- VIEW 삭제
DROP VIEW EMP_VIEW30;

-- 인라인 뷰를 이용한 TOP3 구하기
SELECT ROWNUM,ENAME
FROM EMP
--ORDER BY HIREDATE
;

SELECT ROWNUM, ENAME
FROM (SELECT * FROM EMP ORDER BY ENAME);

-- 입사일이 빠른 사람 5명만(TOP-N)을 얻어오기
SELECT ROWNUM, ENAME, HIREDATE
FROM (SELECT * FROM EMP ORDER BY HIREDATE)
WHERE ROWNUM<6;

SELECT * FROM EMP ORDER BY HIREDATE;

CREATE OR REPLACE VIEW VIEW_HIR
AS
SELECT * FROM EMP ORDER BY HIREDATE;

SELECT ROWNUM, ENAME, HIREDATE FROM VIEW_HIR;

SELECT ROWNUM, ENAME, HIREDATE 
FROM VIEW_HIR
WHERE ROWNUM<6
ORDER BY ENAME;

-- SEQUENCE : 번호 재생기
CREATE SEQUENCE PI_IDX_PK;

SELECT PI_IDX_PK.NEXTVAL
FROM DUAL;

SELECT PI_IDX_PK.CURRVAL
FROM DUAL;

